// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// Authenication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
// Notificaitons
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const SET_NOTIFICATION_READ = 'SET_NOTIFICATION_READ';
export const SET_ALL_NOTIFICATIONS_READ = 'SET_ALL_NOTIFICATIONS_READ';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
// Tickets
export const GET_ALL_TICKETS = 'GET_ALL_TICKETS';
export const GET_ALL_NEW_TICKETS = 'GET_ALL_NEW_TICKETS';
export const GET_TICKET = 'GET_TICKET';
export const CREATE_TICKET = 'CREATE_TICKET';
export const CLEAR_TICKETS = 'CLEAR_TICKETS';
export const CHANGE_STATUS = 'CHANGE_STATUS';
// Replies
export const GET_TICKET_REPLIES = 'GET_TICKET_REPLIES';
export const CREATE_TICKET_REPLY = 'CREATE_TICKET_REPLY';
export const CLEAR_REPLIES = 'CLEAR_REPLIES';
// Timeline
export const GET_TICKET_TIMELINE = 'GET_TICKET_TIMELINE';
// Categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
